# Generated by Django 5.1 on 2024-09-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='fees',
            field=models.IntegerField(max_length=3, null=True),
        ),
    ]
